version: "3.7"

services:
  mongodb:
    container_name: artrade_mongodb
    image: mongo
    restart: unless-stopped
    ports:
      - ${ARTRADE_MONGODB_PORT_27017_OVERRIDE:-27017}:27017

  elasticsearch:
    container_name: artrade_elasticsearch
    image: elasticsearch:8.5.1
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - artrade_network
    ports:
      - ${ARTRADE_ELASTICSEARCH_PORT_9200_OVERRIDE:-9200}:9200
      - ${ARTRADE_ELASTICSEARCH_PORT_9300_OVERRIDE:-9300}:9300
    restart: unless-stopped

  kibana:
    depends_on:
      - elasticsearch
    container_name: artrade_kibana
    image: kibana:8.5.1
    environment:
      - ELASTICSEARCH_HOSTS=http://artrade_elasticsearch:9200
    networks:
      - artrade_network
    ports:
      - ${ARTRADE_KIBANA_PORT_5601_OVERRIDE:-5601}:5601
    restart: unless-stopped

networks:
  artrade_network:
    driver: bridge
